### ISSUE TITLE
Preview without saving

### ISSUE THREAD

**Issue by armansansd** [bitstarr/grav-plugin-draft-preview#3]
Hi ! 
First of all thanks so much for creating this plugin !
I'm trying to add an option to it that would allow the user to preview the content of the page before saving the page.  

I'm not super comfortable with extending grav but do you think it is something possible to do ? 
Any thought about how to do it ? I was wondering if the plugin could save a "preview" version of the content of the page before displaying it. 

Cheers,

**Comment by bitstarr** [comment]
This is a bit out of my scope because it's very tricky, since grav needs something to read from, which are files most the time. Please seek help in the grav discord chat. There may be people around that can provide some ideas to get there. https://chat.getgrav.org/ It's always a good and pretty fast way to get help for any grav topics. People are very welcoming, helpful and generous with code examples.
